### ISSUE TITLE
MPI calls are inefficient

### ISSUE THREAD

**Issue by eschnett** [omlins/adios2-tutorial#14]
The MPI communication pattern in 
https://github.com/omlins/adios2-tutorial/blob/12c3edff5025e5d6f431ec8ab623ce3d9ff330e0/example/mpi_diffusion2D.py#L11 can deadlock: This assumes that the message can be sent before the receiver begins receiving it. It would be better to call `MPI_Sendrecv` https://www.open-mpi.org/doc/v4.0/man3/MPI_Sendrecv.3.php instead.

**Comment by eschnett** [comment]
Correction: It won't deadlock since the processes near the boundaries will only communicate in one direction. However, this will implicitly serialize the MPI halo exchange, which would be inefficient on large numbers of processes.

**Comment by omlins** [comment]
Thanks for your comment. However, the objective of this tutorial is in no way to show how to write high performant or well scaling code (else I would not have chosen Python to begin with ;), used non-blocking MPI etc. ). Instead, the objective of this tutorial is to illustrate with a very simple example some of the awesome features of ADIOS2.
